;             
CREATE USER IF NOT EXISTS "ROOT" SALT '4b8baeddb6c18061' HASH 'afcb8a03e9bafc22dee0ad624f33a71f33e93ba0c127bae28368faa165dbeb59' ADMIN;       
CREATE MEMORY TABLE "PUBLIC"."APPOINTMENT"(
    "APP_ID" VARCHAR(255) NOT NULL,
    "DATE" VARCHAR(255),
    "DOC_ID" VARCHAR(255),
    "DOC_NAME" VARCHAR(255),
    "DOC_SPECIAL" VARCHAR(255),
    "EMAIL" VARCHAR(255),
    "STATUS" VARCHAR(255)
);               
ALTER TABLE "PUBLIC"."APPOINTMENT" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("APP_ID");              
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.APPOINTMENT;             
CREATE MEMORY TABLE "PUBLIC"."DOCTOR"(
    "EMAIL" VARCHAR(255) NOT NULL,
    "CITY" VARCHAR(255),
    "DEGREE" VARCHAR(255),
    "NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "SPECIALIZATION" VARCHAR(255),
    "STATE" VARCHAR(255)
);    
ALTER TABLE "PUBLIC"."DOCTOR" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_7" PRIMARY KEY("EMAIL");    
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.DOCTOR;  
CREATE MEMORY TABLE "PUBLIC"."PERSON"(
    "EMAIL" VARCHAR(255) NOT NULL,
    "PASSWORD" VARCHAR(255)
);   
ALTER TABLE "PUBLIC"."PERSON" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("EMAIL");    
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.PERSON;  
INSERT INTO "PUBLIC"."PERSON" VALUES
('sunitraprivate@gmail.com', '1234');   
